import { DEFAULT_LOCALE } from "./constants";
import type { Locale } from "./types";

const WORDS: Record<Locale, { adjectives: readonly string[]; nouns: readonly string[] }> = {
  tr: {
    adjectives: [
      "mavi",
      "yesil",
      "sari",
      "mor",
      "turuncu",
      "beyaz",
      "siyah",
      "gri",
      "hizli",
      "sakin",
      "kucuk",
      "buyuk",
      "parlak",
      "derin",
      "genis",
      "sicak",
      "serin",
      "tatli",
      "gizli",
      "uzak",
      "yakin",
      "yumusak",
      "keskin",
      "canli",
    ],
    nouns: [
      "kedi",
      "kopek",
      "kus",
      "balik",
      "tilki",
      "kaplan",
      "ayi",
      "kurt",
      "dag",
      "deniz",
      "orman",
      "nehir",
      "bulut",
      "yildiz",
      "kule",
      "kopru",
      "kahve",
      "kitap",
      "anahtar",
      "pencere",
      "bahce",
      "ada",
      "yol",
      "cadir",
    ],
  },
  en: {
    adjectives: [
      "blue",
      "green",
      "amber",
      "violet",
      "orange",
      "white",
      "black",
      "grey",
      "swift",
      "calm",
      "small",
      "grand",
      "bright",
      "deep",
      "wide",
      "warm",
      "cool",
      "sweet",
      "hidden",
      "distant",
      "near",
      "soft",
      "sharp",
      "lively",
    ],
    nouns: [
      "cat",
      "dog",
      "bird",
      "fish",
      "fox",
      "tiger",
      "bear",
      "wolf",
      "hill",
      "ocean",
      "forest",
      "river",
      "cloud",
      "star",
      "tower",
      "bridge",
      "coffee",
      "book",
      "key",
      "window",
      "garden",
      "island",
      "road",
      "tent",
    ],
  },
};

function pick<T>(list: readonly T[]): T {
  const index = Math.floor(Math.random() * list.length);
  return list[index] as T;
}

export function generateRoomSlug(locale: Locale = DEFAULT_LOCALE): string {
  const words = WORDS[locale] ?? WORDS[DEFAULT_LOCALE];
  const number = 1000 + Math.floor(Math.random() * 9000);

  return `${pick(words.adjectives)}-${pick(words.nouns)}-${number}`;
}
